version: "3.8"

services:
  # 1. Database Service
  mysql:
    image: mysql:8
    container_name: menu_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - menu-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 2. Backend Service
  backend:
    build: ./backend
    container_name: menu_backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
      PORT: ${BACKEND_PORT}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - menu-network

  # 3. Frontend Service
  frontend:
    build: ./frontend
    container_name: menu_frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - menu-network

volumes:
  mysql_data:

networks:
  menu-network:
    driver: bridge
